publicKey:
users:
    - code: abc1
      name: Michele Mastrogiovanni
      role: CEO
      image: face1.jpeg
    - code: abc2
      name: Rolando Capasso
      role: Capo Cantiere
      image: face2.jpeg
